name: hmssdk_flutter_example
description: Demonstrates how to use the hmssdk_flutter plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
version: 1.7.2
environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hmssdk_flutter:
    path: ../

  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^0.13.6
  permission_handler: ^10.3.0
  intl: ^0.18.1
  firebase_crashlytics: ^3.3.2
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  firebase_performance: ^0.9.2+2
  firebase_dynamic_links: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^3.1.2
  path_provider: ^2.0.15
  dropdown_button2: ^2.1.4
  focus_detector: ^2.0.1
  flutter_staggered_grid_view: ^0.6.2
  tuple: ^2.0.2
  avatar_glow:  ^2.0.2
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  bot_toast: ^4.0.4
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.1.2
  uni_links: ^0.5.1
  file_picker: ^5.2.10
  draggable_widget: ^2.0.0
  badges: ^3.1.1
  url_launcher: ^6.1.11
  share_plus: ^6.3.4
  flutter_linkify: ^6.0.0
  flutter_foreground_task: ^4.1.0
  image_gallery_saver: ^2.0.2
  wakelock: ^0.6.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/
    - packages/hmssdk_flutter/assets/sdk-versions.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
